### ISSUE TITLE
task1:Unable to open file model_fold_1.h5

### ISSUE THREAD

**Issue by zhaomingwork** [toni-heittola/dcase2020_task1_baseline#1]
Unable to open file (unable to open file: name = '/dcase2020/dcase2020_task1_baseline/system/task1a/learner/data_processing_chain_9f195446c46cc0b161f03c4578ad7b3d/learner_2d8800654b8df776abbcc53518c40084/model_fold_1.h5'

need I go to download it manually? or it is not available now?
thX!

**Comment by toni-heittola** [comment]
Commit 5ee2fda1fc843ac29767f513b0819c29bd235763 fixes this, just pull latest edits. In the parameter file, feature extraction and model learning were switched off by accident. System will train acoustic model now once features are extracted.
