### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by arunodhayan** [toni-heittola/dcase2020_task1_baseline#2]
i tried to use cnn but got this error

  File "/usr/local/lib/python3.6/dist-packages/dcase_util/keras/data.py", line 507, in data_collector
    for i in range(0, data.shape[data.sequence_axis]):
AttributeError: 'FeatureContainer' object has no attribute 'sequence_axis'

**Comment by toni-heittola** [comment]
Without knowing more about the situation where the error occurred, I cannot help. 

So which code you were running, task1a.py or task1b.py? 
What settings/parameters you used? 
Did the system manage to download the dataset, and extract features before entering the model learning stage?

**Comment by arunodhayan** [comment]
for both the task when I tried to use openl3 as feature extractor and CNN as a training method 

feature extractor is happening perfect but before training, it throws the error as above

**Comment by toni-heittola** [comment]
task1a is using OpenL3 as features, and the classifier is based on FNN, whereas task1b is using mel spectrograms as features and CNN classifier. So you have edited parameters or code in both cases, to make CNN with OpenL3 features? 

In order to train CNN classifier, one need to make sure data is segmented in fixed-sized matrices. And most likely this is lacking your task1a setup now, and for task1b segment size specified in the parameters is not valid anymore as openl3 is producing a much lower amount of "features".

**Comment by arunodhayan** [comment]
so I have to reshape the data before training it with CNN for subtask1a

**Comment by toni-heittola** [comment]
Yes,  in this baseline system data is processed in with data processing chain while collecting it for training, and in this chain one can do data sequencing (see example https://github.com/toni-heittola/dcase2020_task1_baseline/blob/master/task1a.yaml#L144). 

So the way to proceed is to create a new parameter setup (similar to https://github.com/toni-heittola/dcase2020_task1_baseline/blob/master/task1a.yaml#L44) and change the feature extraction to openl3 and create your own data processing chain (based on https://github.com/toni-heittola/dcase2020_task1_baseline/blob/master/task1a.yaml#L144) with correct parameters (mainly sequence_length and hop_length) and you should get a working setup.

**Comment by arunodhayan** [comment]
There is a bug in Dcase utils 0.2.13 version
  File "/usr/local/lib/python3.6/dist-packages/dcase_util/decorators/decorators.py", line 14, in __call__
    return self.f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dcase_util/keras/utils.py", line 308, in setup_keras
    keras.backend.tensorflow_backend.set_session(tf.Session(config=config))
UnboundLocalError: local variable 'keras' referenced before assignment

**Comment by toni-heittola** [comment]
I cannot find a code giving the error from the current version of dcase_utils, are you sure you are using latest version? 

Please submit a detailed bug report to dcase_utils repository (https://github.com/DCASE-REPO/dcase_util) as this bug not related the baseline system.

**Comment by arunodhayan** [comment]
yes
