### ISSUE TITLE
Size of int8 in model_size_calculation

### ISSUE THREAD

**Issue by lopusz** [toni-heittola/dcase2020_task1_baseline#3]
Hi @toni-heittola,

Thank you for preparing this baseline, it is very helpful.

I have a short question concerning model size calculation for Task 1B. Currently, it seems that your script counts *int8* as *two bytes*:

 https://github.com/toni-heittola/dcase2020_task1_baseline/blob/98ba3f324f8a07bbf21f4250da7c9205d1d3bae6/model_size_calculation.py#L98

It looks like a typo or shall we consider this in weighting our models for Task 1B?

Thank you in advance for clarification.

Best regards,
Michał

**Comment by toni-heittola** [comment]
This is a bug, thanks for reporting this. It has been fixed in commit 02c31882505d43daf4a665d15a4f2ea15d0872b2

**Comment by lopusz** [comment]
Great! This was lightning-fast answer :)
